## Operations with Matrices

### Setup

In [1]:
import numpy as np

In [7]:
# create vector

x = np.array([1, 2, 3, 4])
print(x)

type(x)

[1 2 3 4]


numpy.ndarray

In [8]:
# create 3x2 matrix

A = np.array([[1,2],[3,4],[4,5]])
print(A)

type(A)

[[1 2]
 [3 4]
 [4 5]]


numpy.ndarray

### Shape

In [10]:
# Numpy arrays have a shape attribute, which can be accessed like so

A.shape

(3, 2)

In [11]:
# For a vector, the shape will correspond with the len(x)

x.shape

(4,)

### Transposition

In [15]:
# We can access the transpose() method of a numpy.ndarray object by

A_T = A.T

# This can also be expressed by
# A_T = A.transpose()

In [16]:
A_T.shape

(2, 3)

### Matrix Addition

In [17]:
B = np.array([[3, 5], [7, 4], [4, 3]])
B

array([[3, 5],
       [7, 4],
       [4, 3]])

In [18]:
# Adding one matrix to another

C = A + B
C

array([[ 4,  7],
       [10,  8],
       [ 8,  8]])

In [19]:
# Adding a matrix to a scalar

D = A + 1
D

array([[2, 3],
       [4, 5],
       [5, 6]])

Numpy can handle operations on arrays of different shapes. A smaller array will be extended to match the shape of a bigger one. This is called broadcasting. The advantage is that it is done under the hood – in C (like any other vectorized operation in Numpy). Actually, we've already used broadcasting in the example above. The scalar was converted to an array of the same shape as the matrix A.
Broadcasting works only if the first array has the same number of rows as the second one, and one of the arrays has only one column (e.g. a matrix Bi,1 can be broadcast across Ai,j). Broadcasting of a scalar value works every time.

### Matrix Multiplication

In [20]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
B = np.array([[2], [4]])
B

array([[2],
       [4]])

In [22]:
# Multiply the matrices

C = np.dot(A, B)
C

# Can also be written as
# C = A.dot(B)

array([[10],
       [22],
       [34]])

### Identity Matrices

An identity matrix (In) is a special square (nxn) matrix which has 1s on the main diagonal and 0s everywhere else.

In [24]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Multiplying an identity matrix with another matrix results in the same matrix

IA = I.dot(A)
IA

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### Determinant

In [26]:
# Determinants can be computed only from square matrices

M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [27]:
det_M = np.linalg.det(M)
det_M

-2.0000000000000004

### Inverse Matrices

The inverse matrix of A with shape (nxn) is denoted as A-1. It is a matrix that results in an identity matrix when multiplied by A (AA-1 = In). This means that if we apply a linear transformation to the matrix with A, it is possible to go back with A-1. This provides a way to cancel the transformation.

In [31]:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [32]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [33]:
# Verify that this inversion is accurate

I = A_inv.dot(A)
I

array([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])