In [2]:
import numpy as np

In [7]:
# ALL 0s matrix

print(np.zeros(5))
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0.]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [8]:
# ALL 1s matrix

print(np.ones((4,2,2), dtype='int32'))

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [9]:
# Any other number

np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [12]:
# Any other number (full_like - can use a.shape with just full for same effect)


a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [15]:
# Random decimal numbers

np.random.rand(4,2)

np.random.random_sample(a.shape)

array([[0.89432795, 0.47596718, 0.64542067, 0.77787167, 0.19889031,
        0.42490003, 0.07964941],
       [0.01107117, 0.9465853 , 0.65677647, 0.79690717, 0.79102811,
        0.52642932, 0.35552806]])

In [18]:
# Random Integer values
# SYNTAX: np.random.randint([<start>,] end[, size])
np.random.randint(7, size=(3,3))

array([[5, 1, 3],
       [5, 2, 5],
       [3, 0, 3]])

In [19]:
# identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
# repeat an array (optional argument axis)

arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [25]:
# Practice question

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z 
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
#Be careful when copying arrays! contiguous memory causes some problemos, both a and b in the below example point to the same thing!

a = np.array([1,2,3])
b = a
b[0] = 100

print(a)

# use a.copy() instead!!

a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[100   2   3]
[1 2 3]
