In [2]:
import numpy as np

In [4]:
# 1D array
# specify datatype as optional argument (dtype='int16' etc)

a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
# 2D array

b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# Get Dimension

print(a.ndim)
print(b.ndim)

1
2


In [11]:
# Get Shape

print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [13]:
#Get Type

print(a.dtype)
print(b.dtype)

int64
float64


In [17]:
# Get Size

print(a.itemsize)
print(b.itemsize)

# Get total size

print(a.nbytes)
print(b.nbytes)

8
8
24
48


In [18]:
### Accessing/Changing specific elements, rows, columns, etc

In [21]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
# Get a specific element [r, c]

print(a[1, 5])

13


In [23]:
# Get a specific row

a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# Get a specific column

a[:, 2]

array([ 3, 10])

In [25]:
# Getting fancy my guy [startindex:endindex:stepsize]

a[0, 1:6:2]

array([2, 4, 6])

In [28]:
# Change elements

a[1,5] = 20
print(a)

a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [31]:
# 3d example<

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

# work outside in

print(b[0,1,1])
b[:


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


4