In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a + 2

array([3, 4, 5, 6])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [6]:
a * 2

array([2, 4, 6, 8])

In [7]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [9]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [10]:
a ** 2

array([ 1,  4,  9, 16])

In [11]:
# Take the sin

np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [12]:
# Take the cos

np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [13]:
# Linear algebra

In [20]:
a = np.full((2,3), 1)
print(a)

b = np.full((3,2), 2)
print(b)

# multiply matrices that are not the same shape
np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [22]:
# Find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

In [23]:
# Statistics

In [24]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.min(stats)
np.min(stats, axis=1)

array([1, 4])

In [26]:
np.min(stats)

1

In [28]:
np.sum(stats, axis=0)

array([5, 7, 9])