In [1]:
import numpy as np

In [5]:
# Load data from file

filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')

array([[ 1, 13, 21],
       [ 2, 42,  1],
       [21, 22, 29]], dtype=int32)

In [11]:
# boolean masking and advanced indexing

print(filedata > 50)
print(filedata[filedata > 5])

# indexing with a list
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

np.any(filedata>50, axis=0)

np.all(filedata > 5, axis = 0)

[[False False False]
 [False False False]
 [False False False]]
[13. 21. 42. 21. 22. 29.]


array([False,  True, False])