# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
a[5] = 1
print(a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [11]:
a = a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
a = np.arange(0,9)
a = a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [15]:
a = np.array([1,2,0,0,4,0])
np.where(a == 0)

(array([2, 3, 5]),)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
np.random.randint(7, size=(3,3))

array([[3, 1, 5],
       [6, 1, 4],
       [2, 2, 5]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [19]:
a = np.random.randint(7, size=(10,10))
print(a)
print(np.min(a))
print(np.max(a))

[[6 1 4 0 1 3 2 6 1 2]
 [4 2 6 1 6 1 4 3 5 2]
 [1 1 6 4 6 4 4 2 3 6]
 [4 4 2 4 1 6 3 5 2 4]
 [1 0 4 3 6 4 2 1 1 5]
 [2 5 0 6 3 1 1 1 3 0]
 [5 0 4 0 3 6 3 5 2 5]
 [5 2 2 5 1 4 5 4 2 6]
 [3 1 0 1 1 0 5 4 4 2]
 [2 2 3 1 1 4 5 2 5 0]]
0
6


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
a = np.random.randint(100, size=(30))
print(a)

np.mean(a)

[30 13 83 48 76 34 25 46 27 83 59 90 54 11 46 99 55 51  1 68 80  8  4 62
 32 41 67 61 88 67]


50.3

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [23]:
a = np.ones((5,5))
z = np.zeros((3,3))
a[1:4,1:4] = z 
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [26]:
b = np.zeros((7,7))
b[1:6,1:6] = a
print(b)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [30]:
all false??

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [34]:
a = np.diag([1,2,3,4])
b = np.zeros((5,5))
b[1:5,0:4] = a
print(b)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [42]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [46]:
a = np.random.randint(100, size=(5,5))
b = np.linalg.norm(a)

a/b

array([[0.0268881 , 0.19205784, 0.03457041, 0.09602892, 0.16132858],
       [0.195899  , 0.1152347 , 0.34186295, 0.09987008, 0.01920578],
       [0.0268881 , 0.13444049, 0.33033948, 0.05377619, 0.0268881 ],
       [0.21510478, 0.15748743, 0.21894594, 0.32265717, 0.01536463],
       [0.3111337 , 0.1690109 , 0.37643336, 0.35338642, 0.01536463]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [51]:
a = np.random.randint(10, size=(10))
m = (a > 3) & (a < 8)
a[m] *= -1
a

array([-7,  8, -6,  1,  2, -6, -5, -5, -4, -5])

#### 29. How to round away from zero a float array ? (★☆☆)

In [57]:
a = np.array([202.45, 40.5, 100.302, 22.127])
np.round(a,0)

array([202.,  40., 100.,  22.])

#### 30. How to find common values between two arrays? (★☆☆)

In [63]:
a = np.random.randint(10, size=10)
b = np.random.randint(10, size=10)
print(a)
print(b)
np.intersect1d(a,b)

[2 0 6 1 4 6 3 2 5 4]
[7 9 8 0 6 5 1 8 1 6]


array([0, 1, 5, 6])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [68]:
# False, because both evaluate to Nan

NameError: name 'none' is not defined

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [71]:
def generate(size):
    for n in range(size):
        yield n
a = np.fromiter(generate(10), dtype="float")
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [73]:
a = np.random.rand(10)
a

array([0.50509268, 0.1537325 , 0.07185304, 0.72887919, 0.03927803,
       0.27953972, 0.045403  , 0.02650853, 0.12355304, 0.42737285])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [74]:
a = np.random.randint(10, size=10)
np.sort(a)

array([0, 0, 1, 1, 3, 3, 4, 4, 5, 6])

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [75]:
a = np.random.randint(10, size=10)
b = np.random.randint(10, size=10)

np.array_equal(a, b)

False

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [81]:
a = np.random.randint(10, size=10)
print(a)
a[np.argmax(a)] = 0
print(a)

[1 2 4 5 1 3 8 6 2 3]
[1 2 4 5 1 3 0 6 2 3]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [85]:
a = np.arange(100)
b = np.random.uniform(0,100)
i = (np.abs(a-b)).argmin()
print(a[i])

49


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [86]:
a = np.random.rand(10)
b = a.astype(int)
print(b)

[0 0 0 0 0 0 0 0 0 0]


#### 59. How to sort an array by the nth column? (★★☆)

In [91]:
a = np.random.randint(10, size=(4,6))
a = a[a[:,1].argsort()]
print(a)

[[8 0 4 5 0 2]
 [1 1 6 9 0 0]
 [5 4 1 9 2 9]
 [5 6 7 1 3 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [92]:
a = np.random.randint(10, size=(4,6))
print((~a.any(axis=0)).any())

False


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [93]:
a = np.array([1,2,3,4,5])
b = np.zeros(len(a) + (len(a)-1)*(3))
b[::4] = a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 72. How to swap two rows of an array? (★★★)

In [95]:
a = np.random.randint(10, size=(4,6))
print(a)
a[[0, 2]] = a[[2, 0]]
print(a)

[[3 9 5 6 3 1]
 [9 3 4 8 4 7]
 [5 4 4 5 8 5]
 [3 7 0 5 2 3]]
[[5 4 4 5 8 5]
 [9 3 4 8 4 7]
 [3 9 5 6 3 1]
 [3 7 0 5 2 3]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [102]:
a = np.random.randint(10, size=(4,6))
a = a.astype(float)
print(a)
a[0,2] = - a[0,2]
print(a)

[[1. 9. 4. 8. 3. 7.]
 [4. 5. 6. 7. 5. 5.]
 [2. 6. 3. 2. 6. 2.]
 [3. 6. 9. 3. 8. 0.]]
[[ 1.  9. -4.  8.  3.  7.]
 [ 4.  5.  6.  7.  5.  5.]
 [ 2.  6.  3.  2.  6.  2.]
 [ 3.  6.  9.  3.  8.  0.]]


#### 83. How to find the most frequent value in an array?

In [120]:
a = np.random.randint(0,10,40)
print(a)

print(np.bincount(a).argmax())




[8 3 3 8 5 9 9 5 6 9 0 9 4 9 9 0 8 9 8 2 1 2 6 7 9 0 7 7 1 0 8 7 6 3 8 7 9
 7 6 4]
9


#### 89. How to get the n largest values of an array (★★★)

In [124]:
a = np.random.randint(0,10,40)
print(a)
n = 10
print(a[np.argsort(a)[-n:]])

[6 4 8 8 3 7 9 7 8 5 1 2 1 2 9 3 8 0 3 8 7 4 3 8 3 2 8 4 6 3 1 1 1 9 4 9 9
 9 8 1]
[8 8 8 8 9 9 9 9 9 9]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [127]:
a = np.random.randint(10, size=(6,10))
print(a)
unique = np.unique(a, axis=0)
print(unique)

[[2 2 7 2 5 4 3 2 9 1]
 [7 9 3 0 1 1 2 1 8 7]
 [2 1 0 8 2 9 8 5 6 0]
 [1 6 0 9 8 8 5 3 3 5]
 [9 0 2 0 3 4 2 1 7 0]
 [2 6 2 6 9 2 1 9 9 3]]
[[1 6 0 9 8 8 5 3 3 5]
 [2 1 0 8 2 9 8 5 6 0]
 [2 2 7 2 5 4 3 2 9 1]
 [2 6 2 6 9 2 1 9 9 3]
 [7 9 3 0 1 1 2 1 8 7]
 [9 0 2 0 3 4 2 1 7 0]]
